model:

  learning_rate3: 0
  learning_rate2: 3e-4
  learning_rate1: 0

  target: ldm.models.diffusion.ddpm.LatentDiffusion
  params:

    # DDPM beta schedule params (linear interpolation)
    linear_start: 0.0015
    linear_end: 0.0155
    timesteps: 1000
    num_timesteps_cond: 1
    log_every_t: 200
    s: 1000

    # The key of the input to the stage in the batch object (e.g. batch["image"])
    loss_type: l2
    first_stage_key: "image"
    cond_stage_key: "class_label"

    # The size of the latent space representation of the image
    image_size: 28
    channels: 1

    # Training options
    cond_stage_trainable: False
    conditioning_key: adm

    # Train only partial model
#    train_condition_only: True
#    ablation_blocks: -1
#    attention_flag: 'spatial'

    # Logging options
    monitor: 'val/loss_simple_ema'

    # Differential privacy options (also requires trainer.max_steps to be set)
    dp_config:
      enabled: True
      epsilon: 1
      delta: 1.0e-5
      max_grad_norm: 1
      poisson_sampling: True
      max_batch_size: 32
      num_noise_sample: 32

      noise_scale_s: 0
      noise_scale: 31.5625

#    scheduler_config: # 10000 warmup steps
#      target: ldm.lr_scheduler.LambdaLinearScheduler
#      params:
#        warm_up_steps: [10000]
#        cycle_lengths: [10000000000000]
#        f_start: [1.e-6]
#        f_max: [1.]
#        f_min: [ 1.]

    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        image_size: 28
        in_channels: 1
        out_channels: 1
        model_channels: 32
        attention_resolutions:
#          - 1
#          - 2
           - 7
        num_res_blocks: 2
        channel_mult:
          - 1
          - 2
          - 2
        num_heads: 2
        use_spatial_transformer: false   # 关闭 cross-attn
#        use_scale_shift_norm: true
#        resblock_updown: true
        num_classes: 10

    cond_stage_config:
      target: ldm.modules.encoders.modules.ClassEmbedder
      params:
        n_classes: 10
        embed_dim: 5
        key: class_label

    first_stage_config:
      target: ldm.models.autoencoder.IdentityFirstStage
      params:
        {}

data:
  batch_size3: 1      # Non-Private Training batch size
  batch_size2: 4096   # Private Training batch size
  batch_size1: 1

  target: main.DataModuleFromConfig
  params:
    batch_size: 4096
    num_workers: 5
    wrap: False 
    train:
      target: ldm.data.fashionmnist.FashionMNISTTrain
#      params:
#        size: 32
    validation:
      target: ldm.data.fashionmnist.FashionMNISTVal
#      params:
#        size: 32

lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 5000
        max_images: 8
        increase_log_steps: False

  trainer:
    benchmark: True
    epochs3: 0
    epochs2: 300
    epochs1: 0

    accelerator: gpu  # need to be gpu instead of ddp for dp settings

    # Baselines: image-based diffusion models DP-edAvg
    # Epsilon:       1
    # Noise:         31.5625
    # Epoch2:        300
    # FID:           165.6
    # Noise multi:   117.2

